### ISSUE TITLE
Unable to connect to local , Binary issue 

### ISSUE THREAD

**Issue by BilalMohammad5** [browserstack/browserstack-local-nodejs#104]
> protractor typeScript/config/bstack_Chrome.js

Connecting local
G:\work repos\efe_Jr_UI_Test_Automation\node_modules\q\q.js:155
                throw e;
                ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at spawn (child_process.js:540:9)
    at Object.execFile (child_process.js:224:17)
    at G:\work repos\efe_Jr_UI_Test_Automation\node_modules\browserstack-local\lib\Local.js:41:34
    at LocalBinary.binaryPath (G:\work repos\efe_Jr_UI_Test_Automation\node_modules\browserstack-local\lib\LocalBinary.js:83:7)
    at Local.getBinaryPath (G:\work repos\efe_Jr_UI_Test_Automation\node_modules\browserstack-local\lib\Local.js:200:19)    at Local.start (G:\work repos\efe_Jr_UI_Test_Automation\node_modules\browserstack-local\lib\Local.js:36:10)
    at G:\work repos\efe_Jr_UI_Test_Automation\typeScript\config\bstack_Chrome.js:35:30
    at new Promise (<anonymous>)
    at beforeLaunch (G:\work repos\efe_Jr_UI_Test_Automation\typeScript\config\bstack_Chrome.js:33:16) {
  errno: 'UNKNOWN',
  code: 'UNKNOWN',
  syscall: 'spawn'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! protractor-typescript-cucumber@4.0.0 bstack_Chrome: `protractor typeScript/config/bstack_Chrome.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protractor-typescript-cucumber@4.0.0 bstack_Chrome script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bilal\AppData\Roaming\npm-cache\_logs\2020-05-04T06_47_04_749Z-debug.log

**Comment by shawnlobo96** [comment]
Hey @BilalMohammad5 

The error message seems to be due to a stale running BrowserstackLocal instance.

Try ending the process via task manager and re-executing your script.

Let me know if this works.
