### ISSUE TITLE
Could not  connect to UI error in Jenkins

### ISSUE THREAD

**Issue by anisharknair** [browserstack/browserstack-local-nodejs#42]
HI,

I am getting the below error in jenkins while executing e2e.

Connecting local error { Error
    at F:\Jenkins\workspace\Angular UI Toolkit\node_modules\browserstack-local\lib\Local.js:57:20
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:548:12)
  name: 'LocalError',
  message: 'Could not connect to UI!',
  extra: undefined }

F:\Jenkins\workspace\Angular UI Toolkit\node_modules\protractor\node_modules\q\q.js:155
                throw e;
                ^
Error
    at F:\Jenkins\workspace\Angular UI Toolkit\node_modules\browserstack-local\lib\Local.js:57:20
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:548:12)

**Comment by mansn** [comment]
I'm experiencing a similar problem. I think the "UI" part in the message comes from the folder name "Angular **UI** Toolkit" in your path to the jenkins job. I'm having a similar issue when trying to run browserstack local, where my path also contain spaces. So I think there's some issue with handling paths which contain spaces. In my case, I'm getting: "Could not connect to Win7!" and **Win7** is a part of the path where the script is executing.

**My logs (similar to yours):**
```
06:18:21 C:\Jenkins\jobs\UFO\jobs\Dev\jobs\Functional (ving.se, Win7 IE11 (browserstack))\workspace>node_modules\.bin\gulp test --browser=bs-win7-ie11 --environment=dev --marketunit=vs --suite=functional 
06:18:24 [06:18:24] Using gulpfile C:\Jenkins\jobs\UFO\jobs\Dev\jobs\Functional (ving.se, Win7 IE11 (browserstack))\workspace\gulpfile.js
06:18:24 [06:18:24] Starting 'test'...
06:18:27 Connecting local
06:18:49 [06:18:49] 'test' errored after 25 s
06:18:49 [06:18:49] LocalError in plugin 'gulp-webdriver'
06:18:49 Message:
06:18:49     Could not connect to Win7!
06:18:49 Details:
06:18:49     extra: undefined
06:18:49 Stack:
06:18:49 LocalError: Could not connect to Win7!
06:18:49     at C:\Jenkins\jobs\UFO\jobs\Dev\jobs\Functional (ving.se, Win7 IE11 (browserstack))\workspace\node_modules\browserstack-local\lib\Local.js:57:20
06:18:49     at ChildProcess.exithandler (child_process.js:197:7)
06:18:49     at emitTwo (events.js:106:13)
06:18:49     at ChildProcess.emit (events.js:191:7)
06:18:49     at maybeClose (internal/child_process.js:877:16)
06:18:49     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by dparne** [comment]
I am having the same issue with Jenkins installed at `C:\Program Files (x86)\Jenkins` in windows 😞

Any solution for this yet?
